import { CountryEnum } from "../../../shared/common/enums/countryEnum";
import { GenderEnum } from "../../../shared/common/enums/genderEnum";
import { HandednessEnum } from "../../../shared/common/enums/handednessEnum";
import { Player } from "../domain";

export const PlayerSeed = (): Player[] => {
  return [
    {
      firstName: "Filipo", // ⚠️ nel JSON era "Filipo", nel tuo esempio "Filippo"
      lastName: "Mezzani",
      birthDate: new Date("2004-01-01"),
      gender: GenderEnum.MALE,
      heightCm: 190,
      weightKg: 0, // ⚠️ default
      handedness: HandednessEnum.LEFT,
      country: CountryEnum.ITA,
      biography: "",
      imageUrl:
        "https://volleybox.net/media/upload/players/17538854998Wy6c.png",
      contact: { email: "" },
      platform: { instagram: "", facebook: "" },
      locked: false,
    },
    {
      firstName: "Niccolò",
      lastName: "Depalma",
      birthDate: new Date("2002-11-09"),
      gender: GenderEnum.MALE,
      heightCm: 194,
      weightKg: 0,
      handedness: HandednessEnum.RIGHT,
      country: CountryEnum.ITA,
      biography: "",
      imageUrl:
        "https://volleybox.net/media/upload/players/16831094616twko.png",
      contact: { email: "" },
      platform: { instagram: "", facebook: "" },
      locked: false,
    },
    {
      firstName: "Andrea",
      lastName: "Polacco",
      birthDate: new Date("2003-03-20"),
      gender: GenderEnum.MALE,
      heightCm: 200,
      weightKg: 0,
      handedness: HandednessEnum.RIGHT,
      country: CountryEnum.ITA,
      biography: "",
      imageUrl:
        "https://volleybox.net/media/upload/players/1573579727b4Dar.png",
      contact: { email: "" },
      platform: { instagram: "", facebook: "" },
      locked: false,
    },
    {
      firstName: "William",
      lastName: "Ravelli",
      birthDate: new Date("1994-01-01"),
      gender: GenderEnum.MALE,
      heightCm: 190,
      weightKg: 0,
      handedness: HandednessEnum.RIGHT,
      country: CountryEnum.ITA,
      biography: "",
      imageUrl:
        "https://volleybox.net/media/upload/players/16739978801KwyJ.png",
      contact: { email: "" },
      platform: { instagram: "", facebook: "" },
      locked: false,
    },
    {
      firstName: "Davide",
      lastName: "Polacco",
      birthDate: new Date("1998-12-15"),
      gender: GenderEnum.MALE,
      heightCm: 192,
      weightKg: 0,
      handedness: HandednessEnum.RIGHT,
      country: CountryEnum.ITA,
      biography: "",
      imageUrl:
        "https://volleybox.net/media/upload/players/1604240338u1CeW.png",
      contact: { email: "" },
      platform: { instagram: "", facebook: "" },
      locked: false,
    },
    {
      firstName: "Matteo",
      lastName: "Dietre",
      // ⚠️ birthDate mancante nel JSON
      birthDate: undefined as unknown as Date,
      gender: GenderEnum.MALE,
      heightCm: 190,
      weightKg: 0,
      handedness: HandednessEnum.RIGHT,
      country: CountryEnum.ITA,
      biography: "",
      imageUrl:
        "https://volleybox.net/media/upload/players/default-player-M.jpg",
      contact: { email: "" },
      platform: { instagram: "", facebook: "" },
      locked: false,
    },
    {
      firstName: "Michele",
      lastName: "Michele",
      birthDate: new Date("1994-04-03"),
      gender: GenderEnum.MALE,
      heightCm: 190,
      weightKg: 0,
      handedness: HandednessEnum.RIGHT,
      country: CountryEnum.ITA,
      biography: "",
      imageUrl:
        "https://volleybox.net/media/upload/players/1751557502CB2zV.png",
      contact: { email: "" },
      platform: { instagram: "", facebook: "" },
      locked: false,
    },
    {
      firstName: "Alessandro",
      lastName: "Acuti",
      birthDate: new Date("2000-08-13"),
      gender: GenderEnum.MALE,
      heightCm: 198,
      weightKg: 0,
      handedness: HandednessEnum.RIGHT,
      country: CountryEnum.ITA,
      biography: "",
      imageUrl:
        "https://volleybox.net/media/upload/players/16718884192VdOU.png",
      contact: { email: "" },
      platform: { instagram: "", facebook: "" },
      locked: false,
    },
    {
      firstName: "Ihosvany",
      lastName: "Hernández Jr.",
      birthDate: new Date("1999-03-13"),
      gender: GenderEnum.MALE,
      heightCm: 194,
      weightKg: 0,
      handedness: HandednessEnum.RIGHT,
      country: CountryEnum.ITA,
      biography: "",
      imageUrl:
        "https://volleybox.net/media/upload/players/big_1745536141ERQ0t.png",
      contact: { email: "" },
      platform: { instagram: "", facebook: "" },
      locked: false,
    },
    {
      firstName: "Stefano",
      lastName: "Dell'Osso",
      birthDate: new Date("2003-01-20"),
      gender: GenderEnum.MALE,
      heightCm: 203,
      weightKg: 0,
      handedness: HandednessEnum.RIGHT,
      country: CountryEnum.ITA,
      biography: "",
      imageUrl:
        "https://volleybox.net/media/upload/players/1604406168a1GCs.png",
      contact: { email: "" },
      platform: { instagram: "", facebook: "" },
      locked: false,
    },
    {
      firstName: "Davide",
      lastName: "Gatti",
      birthDate: new Date("2003-01-01"),
      gender: GenderEnum.MALE,
      heightCm: 175,
      weightKg: 0,
      handedness: HandednessEnum.RIGHT,
      country: CountryEnum.ITA,
      biography: "",
      imageUrl:
        "https://volleybox.net/media/upload/players/17145877899Hfbb.png",
      contact: { email: "" },
      platform: { instagram: "", facebook: "" },
      locked: false,
    },
    {
      firstName: "Lorenzo",
      lastName: "Thei",
      birthDate: new Date("2002-12-30"),
      gender: GenderEnum.MALE,
      heightCm: 182,
      weightKg: 0,
      handedness: HandednessEnum.RIGHT,
      country: CountryEnum.ITA,
      biography: "",
      imageUrl:
        "https://volleybox.net/media/upload/players/17514729903yodZ.png",
      contact: { email: "" },
      platform: { instagram: "", facebook: "" },
      locked: false,
    },
  ];
};
